home:
  devices:
    - id: 1
      name: "Лампа"
      description: "Лампа в зале"
      room: "Зал"
      type: "devices.types.light"
      capabilities:
        - type: "devices.capabilities.on_off"
